### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by YuichiKimura** [KaoriNarita15/study_marking_201511#1]
課題の内容を知らずにここに来た人は成果物がどのようなものかわかりません。
README.mdに今回の課題を記載しましょう。
@79c2950

**Comment by KaoriNarita15** [comment]
README.md を追加致しました。

**Comment by ghost** [comment]
mdはMakrdown記法の拡張子なのでMarkdown記法で書いてあげましょう。
構造化された文書は、読み手によりわかりやすい記述となりますよ！

**Comment by KaoriNarita15** [comment]
README.md　をMarkdown記法による記述に修正致しました。
ご指摘頂きまして、ありがとうございました。

**Comment by YuichiKimura** [comment]
確認しました。
このIssuesはクローズします。
