### ISSUE TITLE
書き方の統一を

### ISSUE THREAD

**Issue by YuichiKimura** [KaoriNarita15/study_marking_201511#2]
演算子の前後にスペース入っている所とそうでないところがあるので統一をしてください。 @79c2950

**Comment by KaoriNarita15** [comment]
修正完了致しました。

> branch_201511_02

**Comment by YuichiKimura** [comment]
確認しました。
まだ何箇所かありますがこのIssuesとしてはクローズします。
この辺は癖だと思うので自分以外が読む場合を考えて
読みやすいコードを目指してください。

**Comment by YuichiKimura** [comment]
masterへのマージお願いします。

**Comment by KaoriNarita15** [comment]
masterへマージ致しました。
こちらへのご報告が遅れまして、失礼致しました。

**Comment by YuichiKimura** [comment]
クローズします。
