### ISSUE TITLE
スペルミス

### ISSUE THREAD

**Issue by YuichiKimura** [KaoriNarita15/study_marking_201511#3]
var myTableLowNum
Lowでは別の意味になってしまいます。  @79c2950

**Comment by KaoriNarita15** [comment]
修正完了致しました。

> branch_201511_03

**Comment by YuichiKimura** [comment]
修正確認しました。@45d0653
masterにマージしてください。

**Comment by KaoriNarita15** [comment]
masterへマージ致しました。
こちらへのご報告が遅れまして、失礼致しました。

**Comment by YuichiKimura** [comment]
クローズします。
